gpus: "2"
workers: 2
device: "cuda"
seed: 42

cudnn:
  benchmark: true
  deterministic: true
  enabled: true

data:
  name: imagenette
  input_w: 224
  input_h: 224
  cls: ['tench', 'English springer', 'cassette player', 'chain saw', 'church', 'French horn', 'garbage truck', 'gas pump', 'golf ball', 'parachute']
  train_path: ./data/imagenette/train
  val_path: ./data/imagenette/val
  test_path: ./data/imagenette/val
  img_ext: [".jpg",]
  augmentation:
    policy_type: "no"

    random_resized_crop:
      enabled: true
      scale: [0.6, 1.0]
      ratio: [0.75, 1.333]

    horizontal_flip_p: 0.5

    random_rotation:
      prob: 0.1
      degrees: 15

    color_jitter:
      prob: 0.3
      args:
        brightness: 0.4
        contrast: 0.4
        saturation: 0.4
        hue: 0.1

    perspective:
      prob: 0.05
      args:
        p: 0.05
        distortion_scale: 0.5
        fill: 127

    gaussian_blur:
      prob: 0.05
      args:
        kernel_size: 3
        sigma: [0.1, 1.0]

    random_erasing:
      prob: 0.3
      args:
        scale: [0.02, 0.25]
        value: "random"

    cutmix_mixup:
      prob: 0.3
model:
  backbone:
    name: mobilenetv3
    mobilenetv3:
      size: small
      pretrained: false
  neck:
    name: gap
    gap:
  head:
    name: stacked_linear
    stacked_linear:
      hidden_channel: 1024  # 1024 - small, 1280 - large
      activation: hardswish
      dropout_rate: 0.2
train:
  ema:
    decay_rate: 0.999
  compile: default
  amp: true
  save_all_epochs: false
  auto_resume: true
  pretrained:
  epochs: 100
  batch_size: 64
  freeze:
  unfreeze_after:
  optimizer:
    name: lion
    lion:
      lr: 0.001
      weight_decay: 0.05
    backbone_lr_mult: 1.0
  lr_scheduler:
    name: cosine
    warmup: 5
    cosine:
      cycles: 0.5
  loss:
    name: ce
    ce:
      weighted: false
  early_stop:

test:
  metric: accuracy
  batch_size: 32
